name: comp-Opsych-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - seaborn
  - matplotlib
  - tensorflow
  - pip
  - pip:
    - statsmodels
